language: java
jdk:
  - openjdk8

dist: trusty

sudo:
  required

cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c "create database peluqueriayadb;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password ''"

services:
  - postgresql

notifications:
  email: false