language: java
jdk:
  - openjdk8

dist: trusty

sudo:
  required

env:
  global:
    - HEREMAPS_API_KEY=fakeAPIKEY
    - EMAIL_USERNAME=fakeEmail00001001@gmail.com
    - EMAIL_PASSWORD=fakePassword

cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c "create database peluqueriayadb;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password ''"

services:
  - postgresql

notifications:
  email: false